services:
  app:
    build: .
    container_name: consumption_meter_back
    ports:
      - "3000:3000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: consumption_meter_user
      DB_PASSWORD: testeshopper
      DB_NAME: consumption_meter_db
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    container_name: consumption_meter_db
    environment:
      POSTGRES_USER: consumption_meter_user
      POSTGRES_PASSWORD: testeshopper
      POSTGRES_DB: consumption_meter_db
    ports:
      - "5432:5432"